### ISSUE TITLE
Please Add Focus Fix Feature

### ISSUE THREAD

**Issue by davidanger** [CarbonROM/android_device_leeco_x2#1]
CarbonROM don't have Focus Fix Feature
Maybe this can help:
https://github.com/RevengeOS-Devices/android_device_leeco_x2/commit/ebbf9c590b83b8c8021533a702d8997fec442a3c

https://github.com/RevengeOS-Devices/android_device_leeco_x2/search?q=focus+fix&unscoped_q=focus+fix

**Comment by Chityanj** [comment]
I know that and I was having that in my unofficial builds
But since its official so I don't think I'm allowed to add leeco extras in official builds and I like it to keep fully stock no bloat  and to fix focus I'm providing you focus fix kernel with every new update

**Comment by davidanger** [comment]
Finished at https://github.com/CarbonROM/android_device_leeco_x2/commit/36690098e78611e8034352dfa88cb83b015108bf
